#############################
# author: mrbacco04@gmail.com
# date: October 2026
# file: universe_catalog.py
#############################

"""Fixed stock universes ranked by the pooled model, as Yahoo Finance tickers.

Each universe is a stable, named set of large index members rather than a
daily screener result, so the model trains on the same stocks every day and
the ranking is not biased toward whatever rallied yesterday. These are
*tracked* universes: index membership changes over time, and every list was
checked against Yahoo Finance price availability on 8 October 2026.

Values are company names; they make news searches far more accurate than
ticker symbols.
"""

from __future__ import annotations

# Dow Jones Industrial Average, including the 2024 additions (Amazon, Nvidia,
# Sherwin-Williams). The ticker list matches FinRL's DOW_30_TICKER (MIT).
DOW_30_LISTINGS = {
    "AAPL": "Apple",
    "AMGN": "Amgen",
    "AMZN": "Amazon",
    "AXP": "American Express",
    "BA": "Boeing",
    "CAT": "Caterpillar",
    "CRM": "Salesforce",
    "CSCO": "Cisco",
    "CVX": "Chevron",
    "DIS": "Walt Disney",
    "GS": "Goldman Sachs",
    "HD": "Home Depot",
    "HON": "Honeywell",
    "IBM": "IBM",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "KO": "Coca-Cola",
    "MCD": "McDonald's",
    "MMM": "3M",
    "MRK": "Merck",
    "MSFT": "Microsoft",
    "NKE": "Nike",
    "NVDA": "Nvidia",
    "PG": "Procter & Gamble",
    "SHW": "Sherwin-Williams",
    "TRV": "Travelers",
    "UNH": "UnitedHealth",
    "V": "Visa",
    "VZ": "Verizon",
    "WMT": "Walmart",
}

# Forty of the largest Nasdaq-100 members (constituents per FinRL's
# NAS_100_TICKER list dated 20 March 2026).
NASDAQ_LEADERS_LISTINGS = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "NVDA": "Nvidia",
    "AMZN": "Amazon",
    "GOOGL": "Alphabet",
    "META": "Meta Platforms",
    "AVGO": "Broadcom",
    "TSLA": "Tesla",
    "COST": "Costco",
    "NFLX": "Netflix",
    "PLTR": "Palantir",
    "AMD": "Advanced Micro Devices",
    "ASML": "ASML",
    "CSCO": "Cisco",
    "TMUS": "T-Mobile US",
    "PEP": "PepsiCo",
    "LIN": "Linde",
    "INTU": "Intuit",
    "ISRG": "Intuitive Surgical",
    "QCOM": "Qualcomm",
    "TXN": "Texas Instruments",
    "AMGN": "Amgen",
    "ADBE": "Adobe",
    "BKNG": "Booking Holdings",
    "AMAT": "Applied Materials",
    "MU": "Micron",
    "LRCX": "Lam Research",
    "KLAC": "KLA",
    "PANW": "Palo Alto Networks",
    "CRWD": "CrowdStrike",
    "ADI": "Analog Devices",
    "GILD": "Gilead Sciences",
    "VRTX": "Vertex Pharmaceuticals",
    "SBUX": "Starbucks",
    "MELI": "MercadoLibre",
    "CDNS": "Cadence Design Systems",
    "SNPS": "Synopsys",
    "ABNB": "Airbnb",
    "PYPL": "PayPal",
    "MRVL": "Marvell Technology",
}

EURO_STOXX_50_LISTINGS = {
    "ADS.DE": "Adidas",
    "ADYEN.AS": "Adyen",
    "AD.AS": "Ahold Delhaize",
    "AI.PA": "Air Liquide",
    "AIR.PA": "Airbus",
    "ALV.DE": "Allianz",
    "ABI.BR": "AB InBev",
    "ARGX.BR": "argenx",
    "ASML.AS": "ASML",
    "CS.PA": "AXA",
    "BAS.DE": "BASF",
    "BAYN.DE": "Bayer",
    "BBVA.MC": "BBVA",
    "SAN.MC": "Banco Santander",
    "BMW.DE": "BMW",
    "BNP.PA": "BNP Paribas",
    "BN.PA": "Danone",
    "DB1.DE": "Deutsche Boerse",
    "DHL.DE": "DHL Group",
    "DTE.DE": "Deutsche Telekom",
    "ENEL.MI": "Enel",
    "ENI.MI": "Eni",
    "EL.PA": "EssilorLuxottica",
    "RACE.MI": "Ferrari",
    "RMS.PA": "Hermes",
    "IBE.MC": "Iberdrola",
    "ITX.MC": "Inditex",
    "IFX.DE": "Infineon",
    "INGA.AS": "ING",
    "ISP.MI": "Intesa Sanpaolo",
    "KER.PA": "Kering",
    "OR.PA": "L'Oreal",
    "MC.PA": "LVMH",
    "MBG.DE": "Mercedes-Benz",
    "MUV2.DE": "Munich Re",
    "NOKIA.HE": "Nokia",
    "NDA-FI.HE": "Nordea",
    "PRX.AS": "Prosus",
    "RHM.DE": "Rheinmetall",
    "SAF.PA": "Safran",
    "SGO.PA": "Saint-Gobain",
    "SAN.PA": "Sanofi",
    "SAP.DE": "SAP",
    "SU.PA": "Schneider Electric",
    "SIE.DE": "Siemens",
    "ENR.DE": "Siemens Energy",
    "UCG.MI": "UniCredit",
    "DG.PA": "Vinci",
    "VOW3.DE": "Volkswagen",
    "WKL.AS": "Wolters Kluwer",
}

FTSE_100_LEADERS_LISTINGS = {
    "AZN.L": "AstraZeneca",
    "SHEL.L": "Shell",
    "HSBA.L": "HSBC",
    "ULVR.L": "Unilever",
    "BP.L": "BP",
    "RIO.L": "Rio Tinto",
    "GSK.L": "GSK",
    "REL.L": "RELX",
    "DGE.L": "Diageo",
    "BATS.L": "British American Tobacco",
    "LSEG.L": "London Stock Exchange Group",
    "RKT.L": "Reckitt",
    "NG.L": "National Grid",
    "GLEN.L": "Glencore",
    "BARC.L": "Barclays",
    "LLOY.L": "Lloyds Banking Group",
    "CPG.L": "Compass Group",
    "AAL.L": "Anglo American",
    "PRU.L": "Prudential",
    "VOD.L": "Vodafone",
    "TSCO.L": "Tesco",
    "BA.L": "BAE Systems",
    "NWG.L": "NatWest",
    "EXPN.L": "Experian",
    "HLN.L": "Haleon",
    "IMB.L": "Imperial Brands",
    "LGEN.L": "Legal & General",
    "CNA.L": "Centrica",
    "SSE.L": "SSE",
    "STAN.L": "Standard Chartered",
    "III.L": "3i Group",
    "ABF.L": "Associated British Foods",
    "RR.L": "Rolls-Royce",
    "BT-A.L": "BT Group",
    "SGE.L": "Sage Group",
    "AV.L": "Aviva",
    "IHG.L": "InterContinental Hotels",
    "WPP.L": "WPP",
    "ANTO.L": "Antofagasta",
    "BRBY.L": "Burberry",
}

DAX_40_LISTINGS = {
    "ADS.DE": "Adidas",
    "AIR.DE": "Airbus",
    "ALV.DE": "Allianz",
    "BAS.DE": "BASF",
    "BAYN.DE": "Bayer",
    "BEI.DE": "Beiersdorf",
    "BMW.DE": "BMW",
    "BNR.DE": "Brenntag",
    "CBK.DE": "Commerzbank",
    "CON.DE": "Continental",
    "DTG.DE": "Daimler Truck",
    "DBK.DE": "Deutsche Bank",
    "DB1.DE": "Deutsche Boerse",
    "DHL.DE": "DHL Group",
    "DTE.DE": "Deutsche Telekom",
    "EOAN.DE": "E.ON",
    "FRE.DE": "Fresenius",
    "G1A.DE": "GEA Group",
    "HNR1.DE": "Hannover Re",
    "HEI.DE": "Heidelberg Materials",
    "HEN3.DE": "Henkel",
    "IFX.DE": "Infineon",
    "MBG.DE": "Mercedes-Benz",
    "MRK.DE": "Merck KGaA",
    "MTX.DE": "MTU Aero Engines",
    "MUV2.DE": "Munich Re",
    "P911.DE": "Porsche",
    "PAH3.DE": "Porsche SE",
    "QIA.DE": "Qiagen",
    "RHM.DE": "Rheinmetall",
    "RWE.DE": "RWE",
    "SAP.DE": "SAP",
    "SRT3.DE": "Sartorius",
    "SIE.DE": "Siemens",
    "ENR.DE": "Siemens Energy",
    "SHL.DE": "Siemens Healthineers",
    "SY1.DE": "Symrise",
    "VOW3.DE": "Volkswagen",
    "VNA.DE": "Vonovia",
    "ZAL.DE": "Zalando",
}

CAC_40_LISTINGS = {
    "AC.PA": "Accor",
    "AI.PA": "Air Liquide",
    "AIR.PA": "Airbus",
    "MT.AS": "ArcelorMittal",
    "CS.PA": "AXA",
    "BNP.PA": "BNP Paribas",
    "EN.PA": "Bouygues",
    "BVI.PA": "Bureau Veritas",
    "CAP.PA": "Capgemini",
    "CA.PA": "Carrefour",
    "ACA.PA": "Credit Agricole",
    "BN.PA": "Danone",
    "DSY.PA": "Dassault Systemes",
    "EDEN.PA": "Edenred",
    "ENGI.PA": "Engie",
    "EL.PA": "EssilorLuxottica",
    "ERF.PA": "Eurofins Scientific",
    "RMS.PA": "Hermes",
    "KER.PA": "Kering",
    "OR.PA": "L'Oreal",
    "LR.PA": "Legrand",
    "MC.PA": "LVMH",
    "ML.PA": "Michelin",
    "ORA.PA": "Orange",
    "RI.PA": "Pernod Ricard",
    "PUB.PA": "Publicis",
    "RNO.PA": "Renault",
    "SAF.PA": "Safran",
    "SGO.PA": "Saint-Gobain",
    "SAN.PA": "Sanofi",
    "SU.PA": "Schneider Electric",
    "GLE.PA": "Societe Generale",
    "STLAP.PA": "Stellantis",
    "STMPA.PA": "STMicroelectronics",
    "TEP.PA": "Teleperformance",
    "HO.PA": "Thales",
    "TTE.PA": "TotalEnergies",
    "URW.PA": "Unibail-Rodamco-Westfield",
    "VIE.PA": "Veolia",
    "DG.PA": "Vinci",
}

# The current FTSE MIB contains 40 companies. Yahoo Finance exposes Milan
# history for 39 of them; STMicroelectronics' Milan symbol (STMMI) is omitted
# because Yahoo does not currently return that local listing. This universe was
# checked against Borsa Italiana's constituent list on 17 July 2026.
FTSE_MIB_MILAN_LISTINGS = {
    "A2A.MI": "A2A",
    "AMP.MI": "Amplifon",
    "AVIO.MI": "Avio",
    "AZM.MI": "Azimut Holding",
    "BMED.MI": "Banca Mediolanum",
    "BMPS.MI": "Banca Monte dei Paschi di Siena",
    "BAMI.MI": "Banco BPM",
    "BPE.MI": "BPER Banca",
    "BC.MI": "Brunello Cucinelli",
    "BZU.MI": "Buzzi",
    "CPR.MI": "Campari",
    "DIA.MI": "DiaSorin",
    "ENEL.MI": "Enel",
    "ENI.MI": "Eni",
    "RACE.MI": "Ferrari",
    "FCT.MI": "Fincantieri",
    "FBK.MI": "FinecoBank",
    "G.MI": "Generali",
    "HER.MI": "Hera",
    "ISP.MI": "Intesa Sanpaolo",
    "INW.MI": "Inwit",
    "IG.MI": "Italgas",
    "IVG.MI": "Iveco Group",
    "LDO.MI": "Leonardo",
    "LTMC.MI": "Lottomatica Group",
    "MB.MI": "Mediobanca",
    "MONC.MI": "Moncler",
    "NEXI.MI": "Nexi",
    "PST.MI": "Poste Italiane",
    "PRY.MI": "Prysmian",
    "REC.MI": "Recordati",
    "SPM.MI": "Saipem",
    "SRG.MI": "Snam",
    "STLAM.MI": "Stellantis",
    "TIT.MI": "Telecom Italia",
    "TEN.MI": "Tenaris",
    "TRN.MI": "Terna",
    "UCG.MI": "UniCredit",
    "UNI.MI": "Unipol",
}

# The Ireland mode is intentionally explicit and finite, rather than using a
# dynamic screener, because the app wants a stable, named market universe.
ISEQ_20_DUBLIN_LISTINGS = {
    "A5G.IR": "AIB Group",
    "BIRG.IR": "Bank of Ireland Group",
    "C5H.IR": "Cairn Homes",
    "DQ7A.IR": "Donegal Investment Group",
    "EG7.IR": "FBD Holdings",
    "GL9.IR": "Glanbia",
    "GVR.IR": "Glenveagh Properties",
    "GRP.IR": "Greencoat Renewables",
    "HMSO.IR": "Hammerson",
    "IR5B.IR": "Irish Continental Group",
    "IRES.IR": "Irish Residential Properties REIT",
    "KMR.IR": "Kenmare Resources",
    "KRZ.IR": "Kerry Group",
    "KRX.IR": "Kingspan Group",
    "MLC.IR": "Malin",
    "MIO.IR": "Mincon Group",
    "OIZ.IR": "Origin Enterprises",
    "PTSB.IR": "Permanent TSB",
    "RYA.IR": "Ryanair Holdings",
    "UPR.IR": "Uniphar",
}

NIKKEI_LEADERS_LISTINGS = {
    "7203.T": "Toyota Motor",
    "6758.T": "Sony Group",
    "9984.T": "SoftBank Group",
    "8306.T": "Mitsubishi UFJ Financial",
    "6861.T": "Keyence",
    "9983.T": "Fast Retailing",
    "8035.T": "Tokyo Electron",
    "6098.T": "Recruit Holdings",
    "4063.T": "Shin-Etsu Chemical",
    "9432.T": "NTT",
    "8058.T": "Mitsubishi Corporation",
    "8031.T": "Mitsui & Co",
    "7974.T": "Nintendo",
    "6501.T": "Hitachi",
    "4502.T": "Takeda Pharmaceutical",
    "7267.T": "Honda Motor",
    "6367.T": "Daikin Industries",
    "8316.T": "Sumitomo Mitsui Financial",
    "6902.T": "Denso",
    "4568.T": "Daiichi Sankyo",
    "6954.T": "Fanuc",
    "7741.T": "Hoya",
    "8766.T": "Tokio Marine",
    "9433.T": "KDDI",
    "6981.T": "Murata Manufacturing",
    "4519.T": "Chugai Pharmaceutical",
    "6273.T": "SMC",
    "6594.T": "Nidec",
    "8411.T": "Mizuho Financial",
    "7011.T": "Mitsubishi Heavy Industries",
}

HANG_SENG_LEADERS_LISTINGS = {
    "0700.HK": "Tencent",
    "9988.HK": "Alibaba",
    "0005.HK": "HSBC",
    "1299.HK": "AIA Group",
    "0939.HK": "China Construction Bank",
    "1398.HK": "ICBC",
    "3690.HK": "Meituan",
    "0941.HK": "China Mobile",
    "2318.HK": "Ping An Insurance",
    "0388.HK": "Hong Kong Exchanges",
    "1810.HK": "Xiaomi",
    "9618.HK": "JD.com",
    "1211.HK": "BYD",
    "3988.HK": "Bank of China",
    "0883.HK": "CNOOC",
    "0857.HK": "PetroChina",
    "2388.HK": "BOC Hong Kong",
    "0175.HK": "Geely Automobile",
    "0001.HK": "CK Hutchison",
    "0016.HK": "Sun Hung Kai Properties",
    "0002.HK": "CLP Holdings",
    "0003.HK": "Hong Kong and China Gas",
    "0027.HK": "Galaxy Entertainment",
    "2020.HK": "Anta Sports",
    "9999.HK": "NetEase",
    "9961.HK": "Trip.com",
    "0669.HK": "Techtronic Industries",
    "0066.HK": "MTR Corporation",
    "0823.HK": "Link REIT",
    "2628.HK": "China Life Insurance",
}
